use altcha::{
    create_challenge, sign_challenge, solve_challenge, verify_solution, Challenge, CounterMode,
    CreateChallengeOptions, HmacAlgorithm, Solution, SolveChallengeOptions, VerifySolutionOptions,
};

fn secret() -> String {
    "test-secret".to_string()
}

// ---------------------------------------------------------------------------
// Round-trip tests
// ---------------------------------------------------------------------------

/// Verifies that a freshly created + solved challenge passes verification.
fn roundtrip(algorithm: &str, cost: u32) {
    let options = CreateChallengeOptions {
        algorithm: algorithm.to_string(),
        cost,
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    };
    let challenge = create_challenge(options).expect("create_challenge failed");
    assert!(challenge.signature.is_some(), "challenge must be signed");

    let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found within timeout");

    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");

    assert!(result.verified, "solution must verify for {algorithm}");
    assert!(!result.expired);
    assert_eq!(result.invalid_signature, Some(false));
    assert_eq!(result.invalid_solution, Some(false));
}

#[test]
fn roundtrip_pbkdf2_sha256() {
    roundtrip("PBKDF2/SHA-256", 100);
}

#[test]
fn roundtrip_pbkdf2_sha384() {
    roundtrip("PBKDF2/SHA-384", 100);
}

#[test]
fn roundtrip_pbkdf2_sha512() {
    roundtrip("PBKDF2/SHA-512", 100);
}

#[test]
fn roundtrip_sha256() {
    roundtrip("SHA-256", 10);
}

#[test]
fn roundtrip_sha384() {
    roundtrip("SHA-384", 10);
}

#[test]
fn roundtrip_sha512() {
    roundtrip("SHA-512", 10);
}

#[cfg(feature = "scrypt")]
#[test]
fn roundtrip_scrypt() {
    roundtrip("SCRYPT", 1024); // N=1024, r=8 (default), p=1 (default)
}

#[cfg(feature = "argon2")]
#[test]
fn roundtrip_argon2id() {
    let options = CreateChallengeOptions {
        algorithm: "ARGON2ID".to_string(),
        cost: 1,              // t_cost (passes)
        memory_cost: Some(8), // m_cost in KiB
        parallelism: Some(1),
        key_prefix: "00".to_string(),
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    };
    let challenge = create_challenge(options).expect("create_challenge failed");
    let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found");
    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");
    assert!(result.verified, "argon2id solution must verify");
}

// ---------------------------------------------------------------------------
// Deterministic mode
// ---------------------------------------------------------------------------

#[test]
fn deterministic_mode_roundtrip() {
    let options = CreateChallengeOptions {
        algorithm: "PBKDF2/SHA-256".to_string(),
        cost: 100,
        counter: Some(0),
        hmac_signature_secret: Some(secret()),
        hmac_key_signature_secret: Some("key-secret".to_string()),
        ..Default::default()
    };
    let challenge = create_challenge(options).expect("create_challenge failed");
    assert!(
        challenge.parameters.key_signature.is_some(),
        "keySignature must be present in deterministic mode"
    );

    let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found");

    // Fast-path verification via key signature.
    let result = verify_solution(VerifySolutionOptions {
        hmac_key_signature_secret: Some("key-secret".to_string()),
        ..VerifySolutionOptions::new(&challenge, &solution, secret())
    })
    .expect("verify_solution failed");

    assert!(result.verified, "deterministic mode must verify");
    assert_eq!(result.invalid_solution, Some(false));
}

/// `CounterMode::String` interoperates with the JS reference. Vector generated by
/// altcha-lib `createChallenge`/`solveChallenge` with `counterMode: 'string'`,
/// SHA-256, cost 10, deterministic counter 42, secret `test-secret`.
#[test]
fn string_counter_mode_matches_js_reference() {
    let challenge: Challenge = serde_json::from_str(
        r#"{"parameters":{"algorithm":"SHA-256","cost":10,"keyLength":32,"keyPrefix":"3cf4a48a065fa0fa96d3a80630e73733","nonce":"647e028a083e3d738d7de0ed42793083","salt":"c6c46275373795af264b50063419ef11"},"signature":"257709e6715640be1d1568a3c1b68e99f5ea19aa320f9b1d7dfaea893a915f66"}"#,
    )
    .expect("invalid challenge JSON");
    let js_derived_key = "3cf4a48a065fa0fa96d3a80630e73733599ed4d57580fa9084baa52ef8694ea9";

    let solution = solve_challenge(SolveChallengeOptions {
        counter_mode: CounterMode::String,
        ..SolveChallengeOptions::new(&challenge)
    })
    .expect("solve_challenge failed")
    .expect("no solution found");
    assert_eq!(solution.counter, 42);
    assert_eq!(solution.derived_key, js_derived_key);

    let result = verify_solution(VerifySolutionOptions {
        counter_mode: CounterMode::String,
        ..VerifySolutionOptions::new(&challenge, &solution, secret())
    })
    .expect("verify_solution failed");
    assert!(result.verified, "{result:?}");

    // The same solution re-derived with the uint32 encoding does not match.
    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");
    assert_eq!(result.invalid_solution, Some(true));

    // Rust-created string-mode challenges roundtrip as well.
    let challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        counter: Some(42),
        counter_mode: CounterMode::String,
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    })
    .expect("create_challenge failed");
    let solution = solve_challenge(SolveChallengeOptions {
        counter_mode: CounterMode::String,
        ..SolveChallengeOptions::new(&challenge)
    })
    .expect("solve_challenge failed")
    .expect("no solution found");
    assert_eq!(solution.counter, 42);
}

// ---------------------------------------------------------------------------
// Negative cases
// ---------------------------------------------------------------------------

#[test]
fn wrong_secret_fails_verification() {
    let options = CreateChallengeOptions {
        algorithm: "PBKDF2/SHA-256".to_string(),
        cost: 100,
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    };
    let challenge = create_challenge(options).expect("create_challenge failed");
    let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found");

    let result = verify_solution(VerifySolutionOptions::new(
        &challenge,
        &solution,
        "wrong-secret",
    ))
    .expect("verify_solution failed");

    assert!(!result.verified);
    assert_eq!(result.invalid_signature, Some(true));
}

/// Regression test: the fallback verification path (no key signature) must reject a
/// solution whose derived key is genuinely correct for its counter but does not satisfy
/// the challenge's `keyPrefix`. Previously only `derivedKey == KDF(counter)` was checked,
/// letting a client submit any counter after a single KDF execution and skip the prefix
/// search entirely.
#[test]
fn fallback_verification_enforces_key_prefix() {
    let mut challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        ..Default::default()
    })
    .expect("create_challenge failed");

    // Learn the honest KDF output for counter 0 with exactly one hash computation: solve a
    // probe copy of the challenge whose keyPrefix is "" (matches immediately, no search).
    let mut probe = challenge.clone();
    probe.parameters.key_prefix = String::new();
    let honest = solve_challenge(SolveChallengeOptions::new(&probe))
        .expect("solve_challenge failed")
        .expect("no solution found");

    // Pick a keyPrefix the honest key is guaranteed not to satisfy: a byte can't be both
    // 0x00 and 0xff.
    let mismatched_prefix = if honest.derived_key.starts_with("00") {
        "ff"
    } else {
        "00"
    };
    challenge.parameters.key_prefix = mismatched_prefix.to_string();
    let signed = sign_challenge(
        &HmacAlgorithm::Sha256,
        &mut challenge.parameters,
        None,
        &secret(),
        None,
    )
    .expect("sign_challenge failed");

    // Submit the honestly-derived key/counter pair (one KDF execution, no prefix search)
    // against the challenge whose signed keyPrefix it does not satisfy.
    let solution = Solution {
        counter: honest.counter,
        derived_key: honest.derived_key,
        time: None,
    };

    let result = verify_solution(VerifySolutionOptions::new(&signed, &solution, secret()))
        .expect("verify_solution failed");

    assert!(
        !result.verified,
        "solution violating key_prefix must not verify"
    );
    assert_eq!(result.invalid_solution, Some(true));
}

/// Regression test: the keyPrefix is case-insensitive in solve and verify, for both the
/// even-length (byte compare) and odd-length (string compare) rules. Verify previously did
/// a case-sensitive string compare, rejecting solutions its own solver accepted, and an
/// odd-length uppercase prefix was unsolvable. The prefix is signed as-is, as it would
/// arrive from another implementation; `create_challenge` itself lowercases it.
#[test]
fn fallback_verification_accepts_uppercase_prefix() {
    for key_prefix in ["0A", "A"] {
        let mut challenge = create_challenge(CreateChallengeOptions {
            algorithm: "SHA-256".to_string(),
            cost: 10,
            key_prefix: key_prefix.to_string(),
            ..Default::default()
        })
        .expect("create_challenge failed");
        assert_eq!(
            challenge.parameters.key_prefix,
            key_prefix.to_ascii_lowercase()
        );

        challenge.parameters.key_prefix = key_prefix.to_string();
        let challenge = sign_challenge(
            &HmacAlgorithm::Sha256,
            &mut challenge.parameters,
            None,
            &secret(),
            None,
        )
        .expect("sign_challenge failed");

        let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
            .expect("solve_challenge failed")
            .expect("no solution found");
        assert!(solution
            .derived_key
            .starts_with(&key_prefix.to_ascii_lowercase()));

        let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
            .expect("verify_solution failed");

        assert!(result.verified, "{key_prefix}: {result:?}");
        assert_eq!(result.invalid_solution, Some(false));
    }
}

/// Regression test: on the key-signature path the client-controlled `derivedKey` is
/// hex-decoded. Non-hex or odd-length input must yield a clean `invalid_solution`, not
/// an `Err` from `verify_solution`.
#[test]
fn key_signature_path_rejects_malformed_derived_key() {
    let challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        counter: Some(0),
        hmac_signature_secret: Some(secret()),
        hmac_key_signature_secret: Some("key-secret".to_string()),
        ..Default::default()
    })
    .expect("create_challenge failed");

    for derived_key in ["zz".repeat(32), "abc".to_string()] {
        let solution = Solution {
            counter: 0,
            derived_key,
            time: None,
        };
        let result = verify_solution(VerifySolutionOptions {
            hmac_key_signature_secret: Some("key-secret".to_string()),
            ..VerifySolutionOptions::new(&challenge, &solution, secret())
        })
        .expect("malformed derivedKey must not return Err");

        assert!(!result.verified, "{:?}", solution.derived_key);
        assert_eq!(result.invalid_signature, Some(false));
        assert_eq!(result.invalid_solution, Some(true));
    }
}

/// Empty secrets count as absent, as in JS: an empty `hmac_signature_secret` leaves the
/// challenge unsigned and an empty `hmac_key_signature_secret` adds no key signature.
#[test]
fn create_challenge_treats_empty_secrets_as_absent() {
    let unsigned = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        hmac_signature_secret: Some(String::new()),
        ..Default::default()
    })
    .expect("create_challenge failed");
    assert_eq!(unsigned.signature, None);

    let without_key_sig = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        counter: Some(1),
        hmac_signature_secret: Some(secret()),
        hmac_key_signature_secret: Some(String::new()),
        ..Default::default()
    })
    .expect("create_challenge failed");
    assert!(without_key_sig.signature.is_some());
    assert_eq!(without_key_sig.parameters.key_signature, None);
}

/// An empty verifier key secret or an empty signed `keySignature` skips the key-signature
/// path (JS: `keySignature && hmacKeySignatureSecret`) and verifies by re-deriving the key.
/// Previously both took the key-signature path and rejected an honest solution.
#[test]
fn verify_treats_empty_key_signature_inputs_as_absent() {
    let challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        counter: Some(1),
        hmac_signature_secret: Some(secret()),
        hmac_key_signature_secret: Some("key-secret".to_string()),
        ..Default::default()
    })
    .expect("create_challenge failed");
    let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found");

    // Empty verifier key secret on a challenge with a real key signature.
    let result = verify_solution(VerifySolutionOptions {
        hmac_key_signature_secret: Some(String::new()),
        ..VerifySolutionOptions::new(&challenge, &solution, secret())
    })
    .expect("verify_solution failed");
    assert!(result.verified, "empty key secret: {result:?}");

    // Empty signed keySignature with a real verifier key secret.
    let mut params = challenge.parameters.clone();
    params.key_signature = Some(String::new());
    let empty_key_sig = sign_challenge(&HmacAlgorithm::Sha256, &mut params, None, &secret(), None)
        .expect("sign_challenge failed");
    let result = verify_solution(VerifySolutionOptions {
        hmac_key_signature_secret: Some("key-secret".to_string()),
        ..VerifySolutionOptions::new(&empty_key_sig, &solution, secret())
    })
    .expect("verify_solution failed");
    assert!(result.verified, "empty keySignature: {result:?}");
}

#[test]
fn tampered_counter_fails_verification() {
    let options = CreateChallengeOptions {
        algorithm: "PBKDF2/SHA-256".to_string(),
        cost: 100,
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    };
    let challenge = create_challenge(options).expect("create_challenge failed");
    let mut solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found");

    // Tamper with the counter.
    solution.counter = solution.counter.wrapping_add(1);

    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");

    assert!(!result.verified);
    assert_eq!(result.invalid_solution, Some(true));
}

#[test]
fn unsigned_challenge_fails_verification() {
    let options = CreateChallengeOptions {
        algorithm: "PBKDF2/SHA-256".to_string(),
        cost: 100,
        hmac_signature_secret: None, // no signing
        ..Default::default()
    };
    let challenge = create_challenge(options).expect("create_challenge failed");
    let solution = Solution {
        counter: 0,
        derived_key: "00".to_string(),
        time: None,
    };

    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");

    assert!(!result.verified);
    assert_eq!(result.invalid_signature, Some(true));
}

/// A challenge expires as soon as the current time passes `expires_at`, with sub-second
/// precision (JS: `expiresAt < Date.now() / 1000`). `expires_at` = the current whole
/// second must already be expired; truncating `now` to seconds used to grant up to 1s
/// of grace.
#[test]
fn expired_challenge_fails_verification() {
    let current_second = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs() as i64;

    let options = CreateChallengeOptions {
        algorithm: "PBKDF2/SHA-256".to_string(),
        cost: 100,
        expires_at: Some(current_second),
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    };
    let challenge = create_challenge(options).expect("create_challenge failed");
    let solution = Solution {
        counter: 0,
        derived_key: "00".to_string(),
        time: None,
    };

    // Guarantee `now` is strictly past `current_second` at verification time.
    std::thread::sleep(std::time::Duration::from_millis(1));
    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");

    assert!(!result.verified);
    assert!(result.expired);
}

/// `expires_at = 0` means "no expiry" (JS: `expiresAt && …`, 0 is falsy).
#[test]
fn zero_expires_at_never_expires() {
    let challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        expires_at: Some(0),
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    })
    .expect("create_challenge failed");
    let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found");

    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");

    assert!(!result.expired);
    assert!(result.verified, "{result:?}");
}

/// Negative `expires_at` lies before the Unix epoch and is always expired.
#[test]
fn negative_expires_at_is_expired() {
    let challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        expires_at: Some(-1),
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    })
    .expect("create_challenge failed");
    let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
        .expect("solve_challenge failed")
        .expect("no solution found");

    let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
        .expect("verify_solution failed");

    assert!(result.expired);
    assert!(!result.verified);
}

/// Regression test: the solver timeout is checked every 10 iterations, independent of the
/// counter values. Previously it was checked only when `counter % 10 == 0`, so a sequence
/// that never hits a multiple of 10 (here: odd counters, as in worker partitioning) never
/// timed out.
#[test]
fn solver_times_out_for_any_counter_sequence() {
    let challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        // Odd-length prefix longer than the 64-char hex key: never matches.
        key_prefix: "0".repeat(65),
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    })
    .expect("create_challenge failed");

    // Solve on a separate thread so a regression fails the test instead of hanging it.
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let result = solve_challenge(SolveChallengeOptions {
            counter_start: 1,
            counter_step: 2,
            timeout_ms: 100,
            ..SolveChallengeOptions::new(&challenge)
        });
        let _ = tx.send(result);
    });

    let result = rx
        .recv_timeout(std::time::Duration::from_secs(5))
        .expect("solver did not time out");
    assert!(result.expect("solve_challenge failed").is_none());
}

/// `timeout_ms: 0` disables the timeout (JS: `timeout && …`) rather than expiring at once.
#[test]
fn zero_timeout_means_no_timeout() {
    let challenge = create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        counter: Some(50),
        hmac_signature_secret: Some(secret()),
        ..Default::default()
    })
    .expect("create_challenge failed");

    let solution = solve_challenge(SolveChallengeOptions {
        timeout_ms: 0,
        ..SolveChallengeOptions::new(&challenge)
    })
    .expect("solve_challenge failed");

    assert!(solution.is_some(), "timeout_ms 0 must not time out");
}

/// Regression test: `key_prefix_length` is capped at half the derived key length. An
/// oversized value used to panic slicing the key; a SHA-256 `key_length` above the 32-byte
/// digest is capped by the actual key, not the requested length.
#[test]
fn key_prefix_length_capped_at_half_key() {
    for (key_length, expected_prefix_bytes) in [(32, 16), (100, 16)] {
        let challenge = create_challenge(CreateChallengeOptions {
            algorithm: "SHA-256".to_string(),
            cost: 10,
            counter: Some(1),
            key_length,
            key_prefix_length: Some(64),
            hmac_signature_secret: Some(secret()),
            ..Default::default()
        })
        .expect("create_challenge failed");

        assert_eq!(
            challenge.parameters.key_prefix.len(),
            expected_prefix_bytes * 2,
            "key_length {key_length}"
        );

        let solution = solve_challenge(SolveChallengeOptions::new(&challenge))
            .expect("solve_challenge failed")
            .expect("no solution found");
        let result = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()))
            .expect("verify_solution failed");
        assert!(result.verified, "key_length {key_length}: {result:?}");
    }
}

/// A non-hex `key_prefix` is a server misconfiguration and is rejected when the challenge
/// is created, rather than surfacing as an `Err` from the client's solve.
#[test]
fn create_challenge_rejects_non_hex_key_prefix() {
    for key_prefix in ["zz", "z", "0g"] {
        let result = create_challenge(CreateChallengeOptions {
            algorithm: "SHA-256".to_string(),
            cost: 10,
            key_prefix: key_prefix.to_string(),
            ..Default::default()
        });
        assert!(
            matches!(result, Err(altcha::Error::InvalidParameters(_))),
            "{key_prefix:?}: {result:?}"
        );
    }

    // Deterministic mode replaces key_prefix with the derived prefix, so it is not checked.
    create_challenge(CreateChallengeOptions {
        algorithm: "SHA-256".to_string(),
        cost: 10,
        counter: Some(1),
        key_prefix: "zz".to_string(),
        ..Default::default()
    })
    .expect("deterministic mode ignores key_prefix");
}

/// A non-hex `key_prefix` in a signed challenge from elsewhere is invalid input regardless
/// of its length: solve and verify both return `InvalidParameters`. Previously an
/// even-length prefix failed hex decoding while an odd-length one made solve run until
/// the timeout and verify report `invalid_solution`.
#[test]
fn solve_and_verify_reject_non_hex_key_prefix() {
    for key_prefix in ["zz", "zzz"] {
        let mut params = create_challenge(CreateChallengeOptions {
            algorithm: "SHA-256".to_string(),
            cost: 10,
            ..Default::default()
        })
        .expect("create_challenge failed")
        .parameters;
        params.key_prefix = key_prefix.to_string();
        let challenge = sign_challenge(&HmacAlgorithm::Sha256, &mut params, None, &secret(), None)
            .expect("sign_challenge failed");

        let solved = solve_challenge(SolveChallengeOptions {
            timeout_ms: 100,
            ..SolveChallengeOptions::new(&challenge)
        });
        assert!(
            matches!(solved, Err(altcha::Error::InvalidParameters(_))),
            "solve {key_prefix:?}: {solved:?}"
        );

        let solution = Solution {
            counter: 0,
            derived_key: "00".repeat(32),
            time: None,
        };
        let verified = verify_solution(VerifySolutionOptions::new(&challenge, &solution, secret()));
        assert!(
            matches!(verified, Err(altcha::Error::InvalidParameters(_))),
            "verify {key_prefix:?}: {verified:?}"
        );
    }
}

// ---------------------------------------------------------------------------
// Canonical JSON
// ---------------------------------------------------------------------------

/// Verifies that canonical JSON produces sorted keys, matching the JS reference.
#[test]
fn canonical_json_sorted_keys() {
    // Reconstruct what the JS `canonicalJSON(parameters)` would produce for a fixed set
    // of parameters. Keys must appear in alphabetical order with no undefined fields.
    use altcha::ChallengeParameters;
    use serde_json;

    let params = ChallengeParameters {
        algorithm: "PBKDF2/SHA-256".to_string(),
        cost: 1000,
        data: None,
        expires_at: None,
        key_length: 32,
        key_prefix: "00".to_string(),
        key_signature: None,
        memory_cost: None,
        nonce: "aabbccdd".to_string(),
        parallelism: None,
        salt: "eeff0011".to_string(),
    };

    let json = serde_json::to_string(&params).unwrap();
    // Keys must be: algorithm, cost, keyLength, keyPrefix, nonce, salt (alphabetical)
    let expected_keys = [
        "algorithm",
        "cost",
        "keyLength",
        "keyPrefix",
        "nonce",
        "salt",
    ];
    let value: serde_json::Value = serde_json::from_str(&json).unwrap();
    let obj = value.as_object().unwrap();
    let actual_keys: Vec<&str> = obj.keys().map(|s| s.as_str()).collect();
    assert_eq!(
        actual_keys, expected_keys,
        "JSON keys must be sorted alphabetically"
    );
}
